services:
  db:
    build:
      context: .
      dockerfile: .docker/database/db.dockerfile
    container_name: rexis-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-rexis}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  traefik:
    image: traefik:v2.11
    container_name: rexis-traefik
    command:
      - "--entrypoints.web.address=:8000"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--api.dashboard=true"   # optional (http://localhost:8080)
    ports:
      - "8000:8000"              # single REST/OpenAPI entrypoint for your CLI
      - "8080:8080"              # dashboard (optional)
    volumes:
      - .docker/ghidra-server/traefik_dynamic.yml:/etc/traefik/dynamic.yml:ro
    restart: unless-stopped

  ghidra-api-1:
    build:
      context: .
      dockerfile: .docker/ghidra-server/ghidra-server.dockerfile
    container_name: rexis-ghidra-api-1
    environment:
      MCPO_API_KEY: "${MCPO_API_KEY:-80cf012afad040e4bb7c940f44f8070c}"
      MCPO_HOST: "0.0.0.0"
      MCPO_PORT: "8001"
      FASTMCP_HOST: "127.0.0.1"
      FASTMCP_PORT: "8000"
      MCP_INPUT_PATHS: "/binaries,/workspace"
      MCP_PRELOAD_MAX: "1"
      GHIDRA_INSTALL_DIR: "${GHIDRA_INSTALL_DIR:-/ghidra}"
      GHIDRA_MAXMEM: "${GHIDRA_MAXMEM:-4G}"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8001/docs >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    expose:
      - "8000"
    volumes:
      - ./data/ghidra/samples:/binaries:ro
      - ./data/ghidra/worker1:/workspace
    restart: unless-stopped
    depends_on:
      - traefik

  ghidra-api-2:
    build:
      context: .
      dockerfile: .docker/ghidra-server/ghidra-server.dockerfile
    container_name: rexis-ghidra-api-2
    environment:
      MCPO_API_KEY: "${MCPO_API_KEY:-80cf012afad040e4bb7c940f44f8070c}"
      MCPO_HOST: "0.0.0.0"
      MCPO_PORT: "8001"
      FASTMCP_HOST: "127.0.0.1"
      FASTMCP_PORT: "8000"
      MCP_INPUT_PATHS: "/binaries,/workspace"
      MCP_PRELOAD_MAX: "1"
      GHIDRA_INSTALL_DIR: "${GHIDRA_INSTALL_DIR:-/ghidra}"
      GHIDRA_MAXMEM: "${GHIDRA_MAXMEM:-4G}"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8001/docs >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    expose:
      - "8000"
    volumes:
      - ./data/ghidra/samples:/binaries:ro
      - ./data/ghidra/worker2:/workspace
    restart: unless-stopped
    depends_on:
      - traefik

volumes:
  pgdata:

networks:
  default:
    name: rexis-ghidra-net
