db_password = "super_secret_password"

# API keys used by Dynaconf via config/settings.toml (@get ...)
openai_api_key = "sk-..."
deepseek_api_key = "dseek-..."

# NOTE: key name must be exactly 'malware_bazaar_api_key'
malware_bazaar_api_key = "malw-bazaar-..."
virus_total_api_key = "vt-..."

# Optional/unused placeholders
decompiler_api_key = "decomp-..."
