db_password = "super_secret_password"

openai_api_key = "sk-xxxx"
deepseek_api_key = "dseek-xxxx"

malware_bazaaar_api_key = "malw-bazaaar-xxxx"
virus_total_api_key = "vt-xxxx"

decompiler_api_key = "decomp-xxxx"
