# General project settings
project_name = "REXIS"
log_level = "INFO"

# Vector DB settings
[db]
host = "localhost"
port = 5432
name = "rexis"
user = "postgres"
password = "@get db_password"

# Model metadata
[models]
openai = {base_url = "https://api.openai.com/v1", api_key = "@get openai_api_key", embedding_model = "text-embedding-3-small", embedding_model_limit=8192, query_model = "gpt-4o-2024-08-06"}
deepseek = {base_url = "https://api.deepseek.com", api_key = "@get deepseek_api_key", embedding_model = "text-embedding-3-small", embedding_model_limit=8192, query_model = "deepseek-chat"}

[pipeline_params]
retriever_top_k = 5
prompt_template = """
You are a malware analysis assistant. Based on the following malware metadata, answer the user's question:

{% for doc in documents %}
Document {{ loop.index }}:
{{ doc.content }}

{% endfor %}

User Question:
{{ query }}

Answer:
"""
