
# General project settings
project_name = "REXIS"
log_level = "INFO"

# Vector DB settings
[db]
host = "localhost"
port = 5432
name = "rexis"
user = "postgres"
password = "@get db_password"

[collection]
malware_bazaar_api_key = "@get malware_bazaar_api_key"

# Ingestion settings
[ingestion]
malpedia_base_url = "https://malpedia.caad.fkie.fraunhofer.de"
default_user_agent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"

[baseline]
virus_total_url = "https://www.virustotal.com/api/v3/files"
virus_total_api_key = "@get virus_total_api_key"

# Model metadata
[models]
openai = {base_url = "https://api.openai.com/v1", api_key = "@get openai_api_key", embedding_model = "text-embedding-3-small", embedding_model_limit=8192, query_model = "gpt-4o-2024-08-06"}
deepseek = {base_url = "https://api.deepseek.com", api_key = "@get deepseek_api_key", embedding_model = "text-embedding-3-small", embedding_model_limit=8192, query_model = "deepseek-chat"}

# Tagger LLM settings
[tagger]
model = "gpt-4.1-mini"
api_key = "@get openai_api_key"
system_prompt = "You are a malware analysis assistant. Your task is to extract 3-7 highly relevant tags from the provided text. Tags should be keywords, entities, malware families, techniques, countries, CVEs, or other important topics.\n\nReturn ONLY a valid Python list of strings, with no explanation or extra text. Example: ['APT28', 'phishing', 'Russia', 'CVE-2023-38831', 'lateral movement'].\n\nText to tag:"
temperature = 0.2
max_tokens = 256

[pipeline_params]
retriever_top_k = 5
prompt_template = """
You are a malware analysis assistant. Based on the following malware metadata, answer the user's question:

{% for doc in documents %}
Document {{ loop.index }}:
{{ doc.content }}

{% endfor %}

User Question:
{{ query }}

Answer:
"""
